export const CHANGE_CURRENT_SONG = 'player/CHANGE_CURRENT_SONG';
// export const CHANGE_CURRENT_MUSIC = 'player/CHANGE_CURRENT_MUSIC';
export const CHANGE_PLAY_LIST = 'player/CHANGE_PLAY_LIST';
export const CHANGE_CURRENT_SONG_INDEX = 'player/CHANGE_CURRENT_SONG_INDEX';

export const CHANGE_SEQUENCE = 'player/CHANGE_SEQUENCE';
export const CHANGR_LYRIC_LIST = 'player/CHANGR_LYRIC_LIST';
export const CHANGE_CURRENT_LYRICINDEX = 'player/CHANGE_CURRENT_LYRICINDEX';